spring.application.name=yalla
stripe.secret.key=pk_test_51SmuEqBVx6WpFMMtXlQ2UVC2JUVsRNxMGGIHNlMEQJu07bwSnq1ZY2F4P6pvJeFm7F06U9jwjTz3n9cz2PnEoOiF0066fO3AKK

# JWT Configuration
app.jwt.issuer=yalla-api
app.jwt.audience=yalla-clients
app.jwt.secret=${JWT_SECRET:Uh0WvRj5qs2sChP0dwTkky/VoudWSk0FVikEDDUKdRU=}
app.jwt.ttl-minutes=60

# API Client credentials (for machine-to-machine authorization)
app.api.client-id=yalla-mobile-app
app.api.client-secret=changeme

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop